### ISSUE TITLE
A/B Test (Split Test) Calculator "Live Demo" Site Not Functioning

### ISSUE THREAD

**Issue by joshkauf** [thumbtack/abba#10]
Greetings. First of all, thank you for your work creating this tool. It's a go-to in my A/B testing toolkit. I have been using your [web-based live demo tool](https://www.thumbtack.com/labs/abba/#) for sometime now and I noticed this past week that the calculator was down. I'm unable to compute results or add another group. When you have a moment please investigate. Thank you.

**Comment by sux13** [comment]
Agree with Josh. This is such a great app and almost mission critical for us. It would be amazing if we can get it back. Thanks so much!

**Comment by tgnourse** [comment]
Thanks for letting us know everyone, we'll get this back up and working again.

**Comment by gostevehoward** [comment]
Thanks Tommy!

I made the demo app under `demo/` accessible via Github pages [here][http://thumbtack.github.io/abba/demo/abba.html], all I had to do was create a gh-pages branch since the demo code was already there. So there is a usable version available, though not as pretty and lacking all the detailed documentation of thumbtack.com/labs/abba. I temporarily updated Readme.md.

**Comment by gostevehoward** [comment]
Also many thanks to @joshkauf and @sux13 for pointing this out!

**Comment by gcpantazis** [comment]
Fixed:

https://www.thumbtack.com/labs/abba/#a=12690%2C30120&b=12446%2C30313&c=12773%2C30522&d=12545%2C30059&e=12898%2C30073&f=12910%2C30251&abba%3AintervalConfidenceLevel=0.95&abba%3AuseMultipleTestCorrection=true

@gostevehoward thanks for the temporary fix; let's leave the github.io site (it's a good backup, plus I'm just using the github.io code on the original demo site as a temporary patch. Need to find a better place to store it on our end).

I'll revert the README in a second.

Thanks all!

**Comment by gostevehoward** [comment]
Thank you @gcpantazis !
