### ISSUE TITLE
What happened to the documentation on the demo page?

### ISSUE THREAD

**Issue by philc** [thumbtack/abba#13]
The documentation on the [demo page](http://thumbtack.github.io/abba/demo/abba.html) was one of the best succinct summaries of AB testing I've come across, and it explained what the tool was doing. The documentation is now gone.

Also, now this portion of the readme is incorrect:

`You can find a usable app and detailed documentation on the live demo.`

I'd suggest either restoring the documentation or moving it to the github wiki and linking to that wiki page from the demo page.

**Comment by philc** [comment]
Looks like the docs were removed in f63cd14a (2012!) but the demo page wasn't updated until very recently?

**Comment by gostevehoward** [comment]
Thanks Phil. I think the demo page at thumbtack.com/labs/abba had the full documentation until recently, and the prose was long ago removed from the github.io version to avoid duplication. Now it looks like the folks at Thumbtack have simply redirected thumbtack.com/labs/abba to the github.io page, which makes life a bit simpler. I think we can restore the documentation. I can also pull in my fixes for #12 from back in January that I never merged upstream. Thanks again for the pointer, hopefully I can tackle these later today.

**Comment by philc** [comment]
Awesome. You've always been impressively responsive on this repo.

**Comment by gostevehoward** [comment]
I've updated the `gh-pages` branch. Let me know if you see any problems. I'm kind of a web frontend dummy and just pulled in a bunch of old CSS that I don't really understand, which is always dangerous...
