### ISSUE TITLE
In the UI, add a "remove" button for the first experimental group

### ISSUE THREAD

**Issue by philc** [thumbtack/abba#7]
We generate links to Abba containing many treatments groups. Sometimes we want to prune down the set of treatments so that we can focus the debrief on the control vs. some of the key experimental groups. If one of the "irrelevant" treatments is the first group in Abba, we can't delete it since there's no remove button.

To work around this, we cut and paste all of the values from one of the interesting treatments into the first row, and then delete the now-blank row.

**Comment by gostevehoward** [comment]
I'll see if I can get the folks at Thumbtack to update the live demo soon...

**Comment by danbirken** [comment]
:thumbsup:
