### ISSUE TITLE
Rename num_trials to something else

### ISSUE THREAD

**Issue by jllopezpino** [thumbtack/abba#8]
Quick suggestion:
In my opinion, num_trials is not descriptive enough and does not match the wording used in the interface. I would rather use num_variations.
Changes would affect stats.py and stats.js.

Thanks for building abba and for listening to my suggestion! Keep it up!

**Comment by gostevehoward** [comment]
Hey José,

I agree the num_trials name is not good, but I think it may not refer to what you think it refers to. Throughout the code, it's used only to refer to the "denominator" in a binomial proportion. So if you had a baseline and two variations, and each group had 100 visitors, some of whom converted, then num_trials refers to the 100 visitors in each group, not to the number of groups/treatments/variations. 

The word "trial" comes from, say, 100 trials of flipping a coin, in the classic binomial example. But it's weird in this context, which is probably what leads to the confusion. It just wasn't a good choice of terminology (and it's not the only bit of ABBA terminology I'd like to change). Perhaps "sample_size" would be the most clear terminology here.

Unfortunately, "num_trials" is used as a public variable name on exposed objects, so it's effectively part of the ABBA API and I can't just change it without breaking backwards compatibility. I have bigger changes in mind for ABBA in the near future and perhaps I'll release it as a backwards-incompatible version 2.0 then and change the API.

I'd love to hear what you think.
